[tool.poetry]
name = "pymake"
version = "0.1.0"
description = "CLI Wrapper"
authors = ["hoangson <lehoangsonsg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.10,<3.11"
PyYAML = "^6.0.1"
pydantic = "^2.3.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
